# Every field in a theme file is optional.

shadow = false
borders = "simple" # Alternatives are "none" and "simple"

[colors]
	# There are 3 ways to select a color:
	# - The 16 base colors are selected by name:
	#       "blue", "light red", "magenta", ...
	# - Low-resolution colors use 3 characters, each <= 5:
	#       "541", "003", ...
	# - Full-resolution colors start with '#' and can be 3 or 6 hex digits:
	#       "#1A6", "#123456", ...

	# If the value is an array, the first valid
	# and supported color will be used.
	# background = "#3B4252"
    background = "black"

	# If the terminal doesn't support custom color (like the linux TTY),
	# non-base colors will be skipped.
	shadow     = "#2E3440"
	view       = "black"

	# An array with a single value has the same effect as a simple value.
	primary   = "#88C0D0"
	secondary = "#81A1C1"
	tertiary  = "#8FBCBB"

	# Hex values can use lower or uppercase.
	title_primary   = "#5E81AC"
	title_secondary = "#81A1C1"

	# Lower precision values can use only 3 digits.
	highlight          = "#4C566A"
	highlight_inactive = "#D8DEE9"
